apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
  - name: ghcr.io/hpcclab/oaas/package-manager
    newName: harbor.129.114.109.85.nip.io/oaas/package-manager
    newTag: latest
  - name: ghcr.io/hpcclab/oaas/class-runtime-manager
    newName: harbor.129.114.109.85.nip.io/oaas/class-runtime-manager
    newTag: latest
  - name: ghcr.io/hpcclab/oaas/storage-adapter
    newTag: dev
  - name: ghcr.io/hpcclab/oaas/invoker
    newName: harbor.129.114.109.85.nip.io/oaas/invoker
    newTag: latest
  - name: ghcr.io/pawissanutt/oaas-rs/gateway
    newName: harbor.129.114.109.85.nip.io/oaas/gateway
    newTag: latest


patches:
  - path: env-configmap.yml

