[package]
name = "oprc-gateway"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-trait="0.1"
axum = "0.7.5"
serde = "1.0.210"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
oprc-proto = {workspace= true}
tonic = "0.12.2"
mobc = "0.8.4"
thiserror = "1.0.63"
http = "1.1.0"
hashbrown = "0.14.5"
base32 = "0.5.1"
bytes = "1.7.1"
envconfig = "0.11.0"
# pingora = { version = "0.3", features = [ "lb" ] }
# pingora-load-balancing = "0.3"