apiVersion: v1
kind: Service
metadata:
  name: {{ include "oprc-compiler.fullname" . }}
  labels:
    {{- include "oprc-compiler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "oprc-compiler.selectorLabels" . | nindent 4 }}
