apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oprc-pm.fullname" . }}-config
  labels:
    {{- include "oprc-pm.labels" . | nindent 4 }}
data:
  # Server configuration
  SERVER_HOST: {{ .Values.config.server.host | quote }}
  SERVER_PORT: {{ .Values.config.server.port | quote }}
  {{- if .Values.config.server.workers }}
  SERVER_WORKERS: {{ .Values.config.server.workers | quote }}
  {{- end }}
  
  # Storage configuration
  STORAGE_TYPE: {{ .Values.config.storage.type | quote }}
  {{- if eq .Values.config.storage.type "etcd" }}
  {{- if .Values.embeddedEtcd.enabled }}
  # Auto-configure etcd endpoints when using embedded CoreOS etcd
  ETCD_ENDPOINTS: "{{ include "oprc-pm.fullname" . }}-etcd:{{ .Values.embeddedEtcd.ports.client }}"
  {{- else }}
  # Use external etcd endpoints
  ETCD_ENDPOINTS: {{ .Values.config.storage.etcd.endpoints | quote }}
  {{- end }}
  ETCD_TLS_INSECURE: {{ .Values.config.storage.etcd.tls.insecure | quote }}
  {{- if .Values.config.storage.etcd.tls.caCertPath }}
  ETCD_CA_CERT_PATH: {{ .Values.config.storage.etcd.tls.caCertPath | quote }}
  {{- end }}
  {{- if .Values.config.storage.etcd.tls.clientCertPath }}
  ETCD_CLIENT_CERT_PATH: {{ .Values.config.storage.etcd.tls.clientCertPath | quote }}
  {{- end }}
  {{- if .Values.config.storage.etcd.tls.clientKeyPath }}
  ETCD_CLIENT_KEY_PATH: {{ .Values.config.storage.etcd.tls.clientKeyPath | quote }}
  {{- end }}
  {{- end }}
  
  # CRM configuration
  CRM_DEFAULT_URL: {{ .Values.config.crm.default.url | quote }}
  CRM_DEFAULT_TIMEOUT: {{ .Values.config.crm.default.timeout | quote }}
  CRM_DEFAULT_RETRY_ATTEMPTS: {{ .Values.config.crm.default.retryAttempts | quote }}
  CRM_HEALTH_CHECK_INTERVAL: {{ .Values.config.crm.healthCheckInterval | quote }}
  CRM_HEALTH_CACHE_TTL: {{ .Values.config.crm.healthCacheTtl | quote }}
  CRM_CIRCUIT_BREAKER_FAILURE_THRESHOLD: {{ .Values.config.crm.circuitBreaker.failureThreshold | quote }}
  CRM_CIRCUIT_BREAKER_TIMEOUT: {{ .Values.config.crm.circuitBreaker.timeout | quote }}
  {{- /* Optional multi-CRM configuration via JSON */}}
  {{- if .Values.config.crm.clustersJson }}
  CRM_CLUSTERS_JSON: |
    {{- .Values.config.crm.clustersJson | nindent 4 }}
  {{- else if .Values.config.crm.clusters }}
  CRM_CLUSTERS_JSON: {{ toJson .Values.config.crm.clusters | quote }}
  {{- end }}
  {{- if .Values.config.crm.defaultCluster }}
  CRM_DEFAULT_CLUSTER: {{ .Values.config.crm.defaultCluster | quote }}
  {{- end }}
  
  # Deployment policy configuration
  DEPLOY_MAX_RETRIES: {{ .Values.config.deployment.maxRetries | quote }}
  DEPLOY_ROLLBACK_ON_PARTIAL: {{ .Values.config.deployment.rollbackOnPartial | quote }}
  
  # Package configuration
  PACKAGE_DELETE_CASCADE: {{ .Values.config.package.deleteCascade | quote }}
  
  # Observability configuration
  OBSERVABILITY_ENABLED: {{ .Values.config.observability.enabled | quote }}
  TRACING_ENABLED: {{ .Values.config.observability.tracing.enabled | quote }}
  {{- if .Values.config.observability.tracing.endpoint }}
  TRACING_ENDPOINT: {{ .Values.config.observability.tracing.endpoint | quote }}
  {{- end }}
  
  # Logging configuration
  RUST_LOG: {{ .Values.logging.level | quote }}
  {{- if .Values.logging.format }}
  LOG_FORMAT: {{ .Values.logging.format | quote }}
  {{- end }}
