apiVersion: v1
kind: Service
metadata:
  name: {{ include "oprc-pm.fullname" . }}
  labels:
    {{- include "oprc-pm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "oprc-pm.selectorLabels" . | nindent 4 }}
