// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeploymentStatusSummary = { 
/**
 * Chosen replication factor (number of environments) for this deployment.
 */
replication_factor: number, 
/**
 * The concrete environments where the deployment is (or will be) placed.
 */
selected_envs?: Array<string>, 
/**
 * Best-effort achieved quorum availability for the selected environments.
 */
achieved_quorum_availability?: number | null, 
/**
 * Optional last error observed during scheduling or rollout.
 */
last_error?: string | null, };
