// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NfrRequirements = { min_throughput_rps: number | null, availability: number | null, cpu_utilization_target: number | null, };
