// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OdgmDataSpec = { 
/**
 * Logical ODGM collection names to materialize. A minimal CreateCollectionRequest will
 * be generated per name with uniform partition/replica/shard settings.
 */
collections?: Array<string>, 
/**
 * Desired partition count per collection (>=1). Partitions drive parallelism and hash space.
 */
partition_count?: number | null, 
/**
 * Desired replica count per partition (>=1). PM selects based on availability NFRs.
 */
replica_count?: number | null, 
/**
 * Shard implementation / consistency strategy (e.g. "mst", "raft").
 */
shard_type?: string | null, 
/**
 * Mapping of environment (target_env) -> list of ODGM node ids assigned for that env
 */
env_node_ids?: { [key in string]: Array<bigint> }, 
/**
 * Optional ODGM log env filter (maps to ODGM_LOG), e.g. "info,openraft=info,zenoh=warn"
 */
log?: string | null, };
