// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageMetadata = { author: string | null, description: string | null, tags: Array<string>, created_at?: string | null, updated_at?: string | null, };
