// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProvisionConfig = { 
/**
 * Explicit container image for the function runtime (required upstream when deploying)
 * If None, deployment controllers will reject the spec instead of applying fallbacks.
 */
container_image?: string | null, port: number | null, max_concurrency: number, need_http2: boolean, cpu_request: string | null, memory_request: string | null, cpu_limit: string | null, memory_limit: string | null, min_scale: number | null, max_scale: number | null, };
