// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsistencyModel } from "./ConsistencyModel";
import type { KeySpecification } from "./KeySpecification";

export type StateSpecification = { key_specs?: Array<KeySpecification>, default_provider?: string, consistency_model: ConsistencyModel, persistent: boolean, serialization_format: string, };
