// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-deployment telemetry configuration for OpenTelemetry integration.
 * Maps to ClassRuntime TelemetrySpec in the CRM.
 */
export type TelemetryConfig = { 
/**
 * Master toggle for telemetry. When false, no OTEL env vars are injected.
 */
enabled?: boolean | null, 
/**
 * Enable trace export (default true when telemetry enabled)
 */
traces?: boolean | null, 
/**
 * Enable metrics export (default true when telemetry enabled)
 */
metrics?: boolean | null, 
/**
 * Enable log export (default false due to high overhead)
 */
logs?: boolean | null, 
/**
 * Trace sampling rate (0.0–1.0). Maps to OTEL_TRACES_SAMPLER_ARG.
 * Default 0.1 (10% sampling). Values > 0.5 may cause high overhead.
 */
sampling_rate?: number | null, 
/**
 * Override service name for OTEL_SERVICE_NAME. If not set, derived from deployment key.
 */
service_name?: string | null, 
/**
 * Additional resource attributes injected as OTEL_RESOURCE_ATTRIBUTES.
 * Format: "key1=value1,key2=value2"
 */
resource_attributes?: { [key in string]: string }, };
