apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oprc-crm.fullname" . }}-config
  labels:
    {{- include "oprc-crm.labels" . | nindent 4 }}
data:
  HTTP_PORT: {{ .Values.config.httpPort | quote }}
  OPRC_CRM_K8S_NAMESPACE: {{ .Values.config.namespace | quote }}
  OPRC_CRM_FEATURES_ODGM: {{ .Values.config.features.odgm | quote }}
  OPRC_CRM_FEATURES_KNATIVE: {{ .Values.config.features.knative | quote }}
  OPRC_CRM_FEATURES_PROMETHEUS: {{ .Values.config.features.prometheus | quote }}
  OPRC_CRM_FEATURES_NFR_ENFORCEMENT: {{ .Values.config.features.nfrEnforcement | quote }}
  OPRC_CRM_FEATURES_HPA: {{ .Values.config.features.hpa | quote }}
  OPRC_CRM_ENFORCEMENT_STABILITY_SECS: {{ .Values.config.enforcement.stabilitySeconds | quote }}
  OPRC_CRM_ENFORCEMENT_COOLDOWN_SECS: {{ .Values.config.enforcement.cooldownSeconds | quote }}
  OPRC_CRM_ANALYZER_INTERVAL_SECS: {{ .Values.config.analyzer.intervalSeconds | quote }}
  OPRC_CRM_PROFILE: {{ .Values.config.profile | quote }}
  RUST_LOG: {{ .Values.logging.level | quote }}
  {{- if .Values.logging.format }}
  LOG_FORMAT: {{ .Values.logging.format | quote }}
  {{- end }}
