{{- if and .Values.knative.operator.enabled .Values.knative.operator.serving.enabled .Values.knative.operator.serving.dns.magic }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "oprc-crm.fullname" . }}-knative-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oprc-crm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "oprc-crm.selectorLabels" . | nindent 8 }}
        job: knative-dns-config
    spec:
      serviceAccountName: {{ include "oprc-crm.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for Knative Serving to be ready..."
          kubectl wait --for=condition=Ready knativeserving/knative-serving -n knative-serving --timeout=300s
          
          echo "Applying Knative default domain configuration..."
          kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.19.0/serving-default-domain.yaml
          
          echo "Knative DNS configuration completed successfully"
{{- end }}
