services:

  gateway:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-gateway
    image: ${IMAGE_PREFIX}/gateway
    ports:
      - "10000:80"
    depends_on: 
      - dev-pm
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
      OPRC_PM_URI: http://dev-pm:80
      OPRC_MAX_POOL_SIZE: 256
  

  router:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-router
    image: ${IMAGE_PREFIX}/router
    ports:
      - "7447:7447"
    environment:
      OPRC_LOG: "DEBUG"
      OPRC_ZENOH_PORT: "7447"
      # OPRC_ZENOH_PEERS: "tcp/router:7447"
  
  
  router-2:
    deploy:
      replicas: 0
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-router
    image: ${IMAGE_PREFIX}/router
    ports:
      - "7448:7447"
    environment:
      OPRC_LOG: "DEBUG"
      OPRC_ZENOH_PORT: "7447"
      OPRC_ZENOH_PEERS: "tcp/router:7447"

  odgm:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-odgm
    image: ${IMAGE_PREFIX}/odgm
    ports:
      - "18001:8080"
    environment:
      RUST_LOG: INFO
      ODGM_CLASS: "test2"
      ODGM_PARTITION_ID: "0"
      ODGM_REPLICA_ID: "0"

  echo-fn:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: dev-echo-fn
    image: ${IMAGE_PREFIX}/echo-fn
    ports:
      - "10001:80"
    environment:
      HTTP_PORT: 80
      # RUST_LOG: INFO
  
  dev-pm:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: dev-pm
    image: ${IMAGE_PREFIX}/dev-pm
    ports:
      - "10002:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
      PM_CLS_LIST: "example!echo=http://echo-fn:80"
      # PM_CLS_LIST: "example!echo=localhost:8080|other=localhost:8080,"
      # result: {"example2": {"echo": "localhost:8080", "other": "localhost:8080"}, "example": {"echo": "localhost:8080", "other": "localhost:8080"}}

  # ui:
  #   image: fullstorydev/grpcui:latest
  #   depends_on:
  #     - gateway
  #   ports:
  #     - 8080:80
  #   command: ["-plaintext", "-port", "80", "gateway:80"]