services:
  builder:
    working_dir: /app/oaas-rs
    build:
      context: build
      dockerfile: dev2.Dockerfile
    entrypoint:
      - "cargo"
      - "build"
      # - "-r"
    image: oprc-dev
    deploy:
      replicas: 0
    volumes: &base_volumes
      - .:/app/oaas-rs
      - ../flare:/app/flare
      - cargo-target:/app/oaas-rs/target
      - cargo-conf:/usr/local/cargo

  odgm-1: &odgm
    image: oprc-dev
    deploy: 
      resources:
        limits:
          cpus: 8
          memory: 8G
    working_dir: /app/oaas-rs
    entrypoint: 
      # - "target/debug/oprc-odgm"
      - "cargo"
      - "run"
      # - "-r"
      - "-p"
      - "oprc-odgm"
    ports:
      - "18001:8080"
    # depends_on: [builder]
    environment: &odgm_env
      # RUST_BACKTRACE: 1
      # OPRC_ZENOH_PEER: "tcp/router:7447"
      # OPRC_ZENOH_LINKSTATE: "true"
      OPRC_ZENOH_BUFFER_SIZE: "16777216"
      ODGM_LOG: info,openraft=warn,zenoh=info,h2=warn,oprc_odgm=debug
      ODGM_NODE_ID: 1
      ODGM_MAX_SESSIONS: 4
      ODGM_MEMBERS: "1,2,3"
      ODGM_COLLECTION: &odgm_collection |
        [
          {"name":"example","partition_count":1,"replica_count":3,"shard_assignments":[], "shard_type":"raft",
          "invocations": {
            "fn_routes": {
              "echo": {"url":"http://echo-fn", "stateless": true}
            }
          },
          "options":{}}
        ]
    volumes: *base_volumes

  odgm-2:
    <<: *odgm
    ports:
      - "18002:8080"
    environment: 
      <<: *odgm_env
      ODGM_NODE_ID: 2  
    
  odgm-3:
    <<: *odgm
    ports:
      - "18003:8080"
    environment:
      <<: *odgm_env
      ODGM_NODE_ID: 3
    
  router:
    image: oprc-dev
    working_dir: /app/oaas-rs
    entrypoint: 
      # - "target/debug/oprc-router"
      - "cargo"
      - "run"
      - "-r"
      - "-p"
      - "oprc-router"
    ports:
      - "7447:7447"
    depends_on: [builder]
    environment:
      OPRC_LOG: "INFO"
      OPRC_ZENOH_PORT: "7447"
      OPRC_ZENOH_BUFFER_SIZE: "16777216"
    volumes: *base_volumes

  
  echo-fn:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: dev-echo-fn
    image: ${IMAGE_PREFIX}/echo-fn
    # ports:
    #   - "10001:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: "INFO"

  # gateway:
  #   image: oprc-dev
  #   working_dir: /app/oaas-rs
  #   entrypoint: 
  #     - "target/debug/oprc-gateway"
  #     # - "cargo"
  #     # - "run"
  #     # - "-r"
  #     # - "-p"
  #     # - "oprc-gateway"
  #   ports:
  #     - "10000:80"
  #   depends_on: 
  #     - dev-pm
  #     - builder
  #   environment:
  #     HTTP_PORT: 80
  #     OPRC_LOG: debug,oprc_gateway=debug,oprc_offload=debug 
  #     OPRC_PM_URI: http://dev-pm:80
  #   volumes: *base_volumes
  
  # dev-pm:
  #   image: oprc-dev
  #   working_dir: /app/oaas-rs
  #   entrypoint: 
  #     - "target/debug/dev-pm"
  #     # - "cargo"
  #     # - "run"
  #     # - "-r"
  #     # - "-p"
  #     # - "tools"
  #     # - "--bin"
  #     # - "dev-pm"
  #   ports:
  #     - "10002:80"
  #   depends_on: [builder]
  #   environment:
  #     HTTP_PORT: 80
  #     RUST_LOG: INFO
  #     PM_CLS_LIST: "example!echo=http://echo-fn:80"
  #   volumes: *base_volumes
    

volumes:
  cargo-target:
  cargo-conf:
