services:
  gateway:
    build:
      context: .
      args:
        - APP_NAME=oprc-gateway
    ports:
      - "10000:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
  
  
  odgm:
    build:
      context: .
      args:
        - APP_NAME=oprc-odgm
    ports:
      - "18001:8001"
    environment:
      RUST_LOG: INFO

  echo-fn:
    build:
      context: .
      args:
        - APP_NAME=echo-fn
    ports:
      - "10001:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
