services:

  router:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-router
    image: ${IMAGE_PREFIX}/router
    ports:
      - "7447:7447"
    environment:
      OPRC_LOG: "INFO"
      OPRC_ZENOH_PORT: "7447"
  

  odgm-1:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-odgm
    image: ${IMAGE_PREFIX}/odgm
    ports:
      - "7448:7447"
      - "18001:8080"
    environment:
      ODGM_LOG: DEBUG,openraft=info,zenoh=info,h2=warn
      OPRC_ZENOH_PEER: "tcp/router:7447"
      ODGM_NODE_ID: 1
      ODGM_COLLECTION: |
        [{"name":"example","partition_count":1,"replica_count":1,"shard_assignments":[{ "replica":[1],"shard_ids":[1]}],"shard_type":"raft","options":{}}]
  
