services:
  _base_image:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    deploy:
      replicas: 0

  
  
  odgm-1:
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    entrypoint: 
      - "oprc-odgm"
    ports:
      - "18001:8080"
    environment:
      RUSTFLAGS: "-Awarnings"
      ODGM_LOG: DEBUG
      OPRC_ZENOH_PEER: "tcp/router:7447"
      ODGM_NODE_ID: 1
      ODGM_COLLECTION: |
        [{"name":"test","partition_count":1,"replica_count":3,"shard_assignments":[{"replica":[1,2,3],"shard_ids":[1,2,3]}],"shard_type":"raft","options":{}}]
      
  
  odgm-2:
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    entrypoint: 
      - "oprc-odgm"
    ports:
      - "18002:8080"
    environment:
      RUSTFLAGS: "-Awarnings"
      ODGM_LOG: DEBUG
      OPRC_ZENOH_PEER: "tcp/router:7447"
      ODGM_NODE_ID: 2
      ODGM_COLLECTION: |
        [{"name":"test","partition_count":1,"replica_count":3,"shard_assignments":[{"replica":[1,2,3],"shard_ids":[1,2,3]}],"shard_type":"raft","options":{}}]
      
  odgm-3:
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    entrypoint: 
      - "oprc-odgm"
    ports:
      - "18003:8080"
    environment:
      RUSTFLAGS: "-Awarnings"
      ODGM_LOG: DEBUG
      OPRC_ZENOH_PEER: "tcp/router:7447"
      ODGM_NODE_ID: 3
      ODGM_COLLECTION: |
        [{"name":"test","partition_count":1,"replica_count":3,"shard_assignments":[{"replica":[1,2,3],"shard_ids":[1,2,3]}],"shard_type":"raft","options":{}}]

  
  gateway:
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    entrypoint: 
      - "oprc-gateway"
    ports:
      - "10000:80"
    depends_on: 
      - dev-pm
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
      OPRC_PM_URI: http://dev-pm:80

  router:
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    entrypoint: 
      - "oprc-router"
    ports:
      - "7447:7447"
    environment:
      OPRC_LOG: "DEBUG"
      OPRC_ZENOH_PORT: "7447"

  echo-fn:
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    entrypoint: 
      - "dev-echo-fn"
    ports:
      - "10001:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
  
  dev-pm:
    image: ghcr.io/pawissanutt/oaas/oprc-rs
    entrypoint: 
      - "dev-pm"
    ports:
      - "10002:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
      PM_CLS_LIST: "example!echo=http://echo-fn:80"
    
