services:
  _base_image:
    build:
      context: build
      dockerfile: dev2.Dockerfile
    image: oprc-dev
    deploy:
      replicas: 0

  odgm-1:
    image: oprc-dev
    working_dir: /app/oaas-rs
    entrypoint: &odgm_entrypoint
      - "cargo"
      - "run"
      - "-r"
      - "-p"
      - "oprc-odgm"
    ports:
      - "18001:8080"
    environment: &odgm_env
      RUST_BACKTRACE: 1
      # OPRC_ZENOH_PEER: "tcp/router:7447"
      # OPRC_ZENOH_LINKSTATE: "true"
      ODGM_LOG: INFO,openraft=warn,zenoh=info,h2=warn
      ODGM_NODE_ID: 1
      ODGM_MAX_SESSIONS: 8
      ODGM_MEMBERS: "1,2,3"
      ODGM_COLLECTION: &odgm_collection |
        [
          {"name":"example","partition_count":72,"replica_count":3,"shard_assignments":[], "shard_type":"raft","options":{}}
        ]
    volumes:
      - .:/app/oaas-rs
      - ../flare:/app/flare
      - cargo-target:/app/oaas-rs/target
      - cargo-conf:/usr/local/cargo

  odgm-2:
    image: oprc-dev
    working_dir: /app/oaas-rs
    entrypoint: *odgm_entrypoint
    ports:
      - "18002:8080"
    environment: 
      <<: *odgm_env
      ODGM_NODE_ID: 2  
    volumes:
      - .:/app/oaas-rs
      - ../flare:/app/flare
      - cargo-target:/app/oaas-rs/target
      - cargo-conf:/usr/local/cargo

  odgm-3:
    image: oprc-dev
    working_dir: /app/oaas-rs
    entrypoint: *odgm_entrypoint
    ports:
      - "18003:8080"
    environment:
      <<: *odgm_env
      ODGM_NODE_ID: 3
    volumes:
      - .:/app/oaas-rs
      - ../flare:/app/flare
      - cargo-target:/app/oaas-rs/target
      - cargo-conf:/usr/local/cargo

  router:
    image: oprc-dev
    working_dir: /app/oaas-rs
    entrypoint: 
      - "cargo"
      - "run"
      - "-r"
      - "-p"
      - "oprc-router"
    ports:
      - "7447:7447"
    environment:
      OPRC_LOG: "INFO"
      OPRC_ZENOH_PORT: "7447"
    volumes:
      - .:/app/oaas-rs
      - ../flare:/app/flare
      - cargo-target:/app/oaas-rs/target
      - cargo-conf:/usr/local/cargo

volumes:
  cargo-target:
  cargo-conf:
