services:

  gateway:
    build:
      context: .
      args:
        APP_NAME: oprc-gateway
    image: ${IMAGE_PREFIX}/gateway
    ports:
      - "10000:80"
    depends_on: 
      - dev-pm
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
      OPRC_PM_URI: http://dev-pm:80
      OPRC_MAX_POOL_SIZE: 256
  
  
  odgm:
    build:
      context: .
      args:
        APP_NAME: oprc-odgm
    image: ${IMAGE_PREFIX}/odgm
    ports:
      - "18001:8001"
    environment:
      RUST_LOG: INFO

  echo-fn:
    build:
      context: .
      args:
        APP_NAME: dev-echo-fn
    image: ${IMAGE_PREFIX}/echo-fn
    ports:
      - "10001:80"
    environment:
      HTTP_PORT: 80
      # RUST_LOG: INFO
  
  dev-pm:
    build:
      context: .
      args:
        APP_NAME: dev-pm
    image: ${IMAGE_PREFIX}/dev-pm
    ports:
      - "10002:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO
      PM_CLS_LIST: "example!echo=http://echo-fn:80,device!register=http://iot-integration|rpc=http://iot-integration"
      # PM_CLS_LIST: "example!echo=localhost:8080|other=localhost:8080,"
      # result: {"example2": {"echo": "localhost:8080", "other": "localhost:8080"}, "example": {"echo": "localhost:8080", "other": "localhost:8080"}}

  # ui:
  #   image: fullstorydev/grpcui:latest
  #   depends_on:
  #     - gateway
  #   ports:
  #     - 8080:80
  #   command: ["-plaintext", "-port", "80", "gateway:80"]