services:

  crm:
    deploy:
      replicas: 0
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-crm
        BUILD_PROFILE: ${BUILD_PROFILE:-release}
    image: ${IMAGE_PREFIX}/crm:${IMAGE_VERSION}
    environment:
      RUST_LOG: INFO
      HTTP_PORT: 80

  pm:
    deploy:
      replicas: 0
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-pm
        BUILD_PROFILE: ${BUILD_PROFILE:-release}
    image: ${IMAGE_PREFIX}/pm:${IMAGE_VERSION}
    environment:
      HTTP_PORT: 80
      RUST_LOG: INFO

  router:
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-router
        BUILD_PROFILE: ${BUILD_PROFILE:-release}
    image: ${IMAGE_PREFIX}/router:${IMAGE_VERSION}
    # network_mode: "host"
    ports:
      - "7447:7447"
    environment:
      OPRC_LOG: "INFO"
      OPRC_ZENOH_PORT: "7447"
  

  odgm-1: &odgm
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: oprc-odgm
        BUILD_PROFILE: ${BUILD_PROFILE:-release}
    deploy:
      resources:
        reservations:
          cpus: "8"
        limits:
          cpus: "8"
    image: ${IMAGE_PREFIX}/odgm:${IMAGE_VERSION}
    # network_mode: "host"
    # ports:
    #   - "18001:8080"
    environment: &odgm_env
      ODGM_LOG: INFO,oprc_odgm=info,openraft=info,zenoh=info,h2=warn
      ODGM_NODE_ID: 1
      ODGM_MAX_SESSIONS: 4
      ODGM_MEMBERS: "1,2,3"
      ODGM_COLLECTION: |
        [
          {"name":"example.record","partition_count":4,"replica_count":3,"shard_assignments":[], "shard_type":"raft",
          "invocations": {
            "fn_routes": {
              "echo": {"url":"http://echo-fn", "stateless": true, "standby": false, "active_group": []},
              "random": {"url":"http://random-fn", "stateless": false, "standby": false, "active_group": []},
              "log": {"url":"http://num-log-fn", "stateless": false, "standby": false, "active_group": []}
            }
          },
          "options":{}}
        ]
    

  odgm-2:
    <<: *odgm
    environment: 
      <<: *odgm_env
      ODGM_NODE_ID: 2  

  odgm-3:
    <<: *odgm
    environment: 
      <<: *odgm_env
      ODGM_NODE_ID: 3

  echo-fn:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: dev-echo-fn
        BUILD_PROFILE: ${BUILD_PROFILE:-release}
    image: ${IMAGE_PREFIX}/echo-fn:${IMAGE_VERSION}
    ports:
      - "10001:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: "info,h2=warn,zenoh=info"

      
  random-fn:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: dev-random-fn
        BUILD_PROFILE: ${BUILD_PROFILE:-release}
    image: ${IMAGE_PREFIX}/random-fn:${IMAGE_VERSION}
    ports:
      - "10002:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: "info,h2=warn,zenoh=info"

  num-log-fn:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: dev-num-log-fn
        BUILD_PROFILE: ${BUILD_PROFILE:-release}
    image: ${IMAGE_PREFIX}/num-log-fn:${IMAGE_VERSION}
    ports:
      - "10003:80"
    environment:
      HTTP_PORT: 80
      RUST_LOG: "info,h2=warn"
  