= Reference
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

== Gateway REST API Reference

=== Invocation API

* [x] POST `/api/class/<class>/<partition>/objects/<object_id>/invokes/<method_id>`
+
invoke a method on an object

* [x] POST `/api/class/<class>/<partition>/invokes/<method_id>`
+
invoke a stateless method

* [x] GET: `/api/class/<class>/<partition>/objects/<object_id>`
+
get an object from the database
+
response: <<ObjData,ObjData>>

* [x] PUT: `/api/class/<class>/<partition>/objects/<object_id>`
+
put an object into the database
+
request: <<ObjData,ObjData>>
+
response: empty

== Zenoh API Reference

===  Invocation API

* [x] GET: `oprc/<class>/<partition>/invokes/<method_id>`
+
invoke a stateless method
+
request: <<InvocationRequest,InvocationRequest>>
+
response: <<InvocationResponse,InvocationResponse>>

* [x] GET: `oprc/<class>/<partition>/objects/<object_id>/invokes/<method_id>`
+
invoke a method on an object
+
request: <<ObjectInvocationRequest,ObjectInvocationRequest>>
+
response: <<InvocationResponse,InvocationResponse>>



* [ ] PUT: `oprc/<class>/<partition>/invokes/<method_id>/async`
+
asynchronously invoke a stateless method
+
request: <<InvocationRequest,InvocationRequest>>
+
response: <<InvocationResponse,InvocationResponse>>

* [ ] PUT: `oprc/<class>/<partition>/objects/<object_id>/invokes/<method_id>/async`
+
asynchronously invoke a method on an object
+
request: <<ObjectInvocationRequest,ObjectInvocationRequest>>
+
response: <<InvocationResponse,InvocationResponse>>


=== Object API

* [x] PUT: `oprc/<class>/<partition>/objects/<object_id>`
+
put an object into the database
+
payload: <<ObjData,ObjData>>


* [ ] PUT: `oprc/<class>/<partition>/objects/<object_id>/merge`
+
merge an object into the database
+
payload: <<ObjData,ObjData>>


* [ ] GET: `oprc/<class>/<partition>/objects/<object_id>/merge`
+
merge an object into the database and get the merged result back.
+
request: <<ObjData,ObjData>>
+
response: <<ObjData,ObjData>>


* [x] GET: `oprc/<class>/<partition>/objects/<object_id>/set`
+
set an object into the database. The difference from `PUT oprc/<class>/<partition>/objects/<object_id>` is that this method will wait for the object to be persisted before returning.
+
payload: <<ObjData,ObjData>>


* [x] GET: `oprc/<class>/<partition>/objects/<object_id>`
+
get an object from the database
+
response: <<ObjData,ObjData>>


* [ ] GET: `oprc/<class>/<partition>/objects/<object_id>/values/<field_id>`
+
get a field from an object
+
response: <<ObjData,ValData>>


* [ ] SUB: `oprc/<class>/<partition>/objects/<object_id>/change`
+
subscribe to an object change's events
+
response: <<ObjData,ObjData>>

* [x] DELETE: `oprc/<class>/<partition>/objects/<object_id>`
+
delete an object from the database

=== Zrpc reference

* [x] GET: `oprc/<class>/<partition>/raft-append/<replica_id>`
+
Raft's AppendEntries RPC 

* [x] GET: `oprc/<class>/<partition>/raft-vote/<replica_id>`
+
Raft's Vote RPC

* [x] GET: `oprc/<class>/<partition>/raft-snapshot/<replica_id>`
+
Raft's Snapshot RPC

* [x] GET: `oprc/<class>/<partition>/ops/<replica_id>`
+
Sends an operation to a replica

== Data reference

=== Path data reference

* `class`: string
* `partition`: unsigned int 16
* `object_id`: unsigned int 64
* `method_id`: string
* `field_id`: unsigned int 16
* `replica_id`: unsigned int 64

NOTE: Protobuf does not support unsigned int 16. If it is shown as unsigned int 16 in the data reference, the value must not overflow when encoded in Protobuf.

=== Protobuf reference

* [[ObjData]] object data
+
[source,protobuf]
----
message ObjData {
  optional ObjMeta metadata = 1;
  map<uint32, ValData> entries = 2;
}

message ObjMeta {
  string cls_id = 1;
  uint32 partition_id = 2;
  uint64 object_id = 3;
}

message ValData {
  oneof data {
    bytes byte = 1;
    bytes crdt_map = 2;
  }
}
----

* [[InvocationRequest]] invocation request
+
[source,protobuf]
----
message InvocationRequest{
    string cls_id = 3;
    string fn_id = 4;
    map<string, string> options = 5;
    bytes payload = 6;
}
----

* [[InvocationResponse]] invocation response
+
[source,protobuf]
----
message InvocationResponse{
    optional bytes payload = 1;
    ResponseStatus status = 2;
}

enum ResponseStatus{
    OKAY=0;
    ERROR=1;
}
----

* [[ObjectInvocationRequest]] object invocation request
+
[source,protobuf]
----
message ObjectInvocationRequest{
    int32 partition_id = 1;
    uint64 object_id = 2;
    string cls_id = 3;
    string fn_id = 4;
    map<string, string> options = 5;
    bytes payload = 6;
}
----
