[package]
name = "oprc-pb"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = {workspace = true}
prost-types = "0.13"
tonic = { workspace = true, features = ["server"]}
serde = { workspace = true, features = ["derive"] }
# bytes = { version = "1.7.1", features = []}

[build-dependencies]
tonic-build = { version = "0.12", features = ["prost"] }

[package.metadata.cargo-machete]
ignored = ["prost", "serde"]