apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - package-manager.yml

secretGenerator:
  - name: oaas-pm-data
    literals:
      - OPRC_DB_PKG_HOST="arango-cluster"
      - OPRC_DB_PKG_PORT="8529"
      - OPRC_DB_PKG_DB="oaas"
      - OPRC_DB_PKG_USER="root"
      - OPRC_DB_PKG_PASS="changeme"
    options:
      disableNameSuffixHash: true

configMapGenerator:
  - name: oaas-env-config
    options:
      disableNameSuffixHash: true
    files:
      - OPRC_PM_ENV=oprc-env.yml
  - name: oaas-pm-config
    options:
      disableNameSuffixHash: true
    literals:
      - JAVA_OPTIONS=-Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:MaxDirectMemorySize=512m
      - QUARKUS_CONSOLE_COLOR=true
      - QUARKUS_HTTP_CORS=true
      - OPRC_LOG=DEBUG
      - KAFKA_BOOTSTRAP_SERVERS=oaas-kafka-bootstrap:9092