name: example
functions:
  - name: record.echo
    type: TASK
    provision:
      knative:
        image: harbor.129.114.109.85.nip.io/oaas/echo-fn
        port: 8080
        requestsCpu: "1"
        limitsCpu: "1"
        requestsMemory: "512Mi"
        limitsMemory: "512Mi"
        minScale: 0
        maxScale: 30
        targetConcurrency: 4
    config:
      offloadingMode: JSON
      http2: true
      custom:
        RUST_LOG: INFO
classes:
  - name: record
    stateType: FILES
    objectType: SIMPLE
    parents: ['builtin.base']
    functions:
      - name: echo
        function: .record.echo
        outputCls: none
        noMain: true
        defaultArgs:
          INPLACE: "true"

deployments:
  - key: example.record
    partitionCount: 3
    replicaCount: 1
    shardType: raft
    targetEnvs: 
      - cloud-1
      # - edge-1
      # - edge-2

