[package]
name = "oprc-test-utils"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
chrono.workspace = true
kube.workspace = true
k8s-openapi.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
nanoid = "0.4"

# Bring rustls from workspace (with aws-lc-rs feature) so test-utils can call CryptoProvider
rustls.workspace = true

# Optional gRPC helpers
oprc-grpc.workspace = true
tonic.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
# none
