// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeploymentCondition = "PENDING" | "DEPLOYING" | "RUNNING" | "DOWN" | "DELETED";
