// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentCondition } from "./DeploymentCondition";

export type DeploymentFilter = { package_name: string | null, class_key: string | null, target_env: string | null, condition: DeploymentCondition | null, };
