// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvisionConfig } from "./ProvisionConfig";
import type { QosRequirement } from "./QosRequirement";

export type FunctionDeploymentSpec = { function_key: string, 
/**
 * Short human-readable description for the function
 */
description?: string | null, 
/**
 * Optional available location / environment name where this function may run (e.g., "edge", "cloud")
 */
available_location?: string | null, 
/**
 * Per-function QoS requirements (inherited from package metadata or analyzer)
 */
qos_requirement?: QosRequirement | null, 
/**
 * Optional provision configuration copied from package (container image, ports, knative hints)
 */
provision_config?: ProvisionConfig | null, 
/**
 * Arbitrary config key/value pairs from package metadata (injected as ENV to runtimes)
 */
config?: { [key in string]: string }, };
