// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionAccessModifier } from "./FunctionAccessModifier";

export type FunctionBinding = { name: string, function_key: string, access_modifier: FunctionAccessModifier, stateless: boolean, parameters: Array<string>, };
