// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentCondition } from "./DeploymentCondition";
import type { DeploymentStatusSummary } from "./DeploymentStatusSummary";
import type { FunctionDeploymentSpec } from "./FunctionDeploymentSpec";
import type { NfrRequirements } from "./NfrRequirements";
import type { OdgmDataSpec } from "./OdgmDataSpec";
import type { TelemetryConfig } from "./TelemetryConfig";

export type OClassDeployment = { key: string, package_name: string, class_key: string, 
/**
 * Explicit target environments to deploy to. If empty, the system will
 * select environments automatically based on availability and NFRs.
 */
target_envs?: Array<string>, 
/**
 * Optional allow-list of environments that are eligible for automatic
 * selection. If empty, all known environments are considered.
 */
available_envs?: Array<string>, nfr_requirements: NfrRequirements, 
/**
 * Per-environment template overrides. Key = environment/cluster name,
 * Value = template name or alias. Highest precedence for that env.
 */
env_templates?: { [key in string]: string }, functions: Array<FunctionDeploymentSpec>, condition: DeploymentCondition, odgm?: OdgmDataSpec | null, 
/**
 * Per-deployment telemetry/observability configuration
 */
telemetry?: TelemetryConfig | null, 
/**
 * Optional runtime status summary populated by the Package Manager.
 */
status?: DeploymentStatusSummary | null, created_at?: string | null, updated_at?: string | null, };
