// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionType } from "./FunctionType";
import type { ProvisionConfig } from "./ProvisionConfig";

export type OFunction = { key: string, function_type: FunctionType, description: string | null, provision_config: ProvisionConfig | null, config: { [key in string]: string }, };
