// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OClass } from "./OClass";
import type { OClassDeployment } from "./OClassDeployment";
import type { OFunction } from "./OFunction";
import type { PackageMetadata } from "./PackageMetadata";

export type OPackage = { name: string, version: string | null, metadata: PackageMetadata, classes: Array<OClass>, functions: Array<OFunction>, dependencies: Array<string>, deployments: Array<OClassDeployment>, };
