// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResourceRequirements = { cpu_request?: string | null, memory_request?: string | null, cpu_limit?: string | null, memory_limit?: string | null, };
