[package]
name = "oprc-dp-storage"
version = "0.1.0"
edition = "2021"

[features]
default = ["memory"]
memory = []
redb = ["dep:redb"]
fjall = ["dep:fjall"]
rocksdb = ["dep:rocksdb"]

[dependencies]
# Core dependencies
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
smallvec = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
regex = { workspace = true }

# Optional storage backends
redb = { version = "2.0", optional = true }
fjall = { version = "2.0", optional = true }
rocksdb = { version = "0.23", optional = true }

# Testing
[dev-dependencies]
tempfile = { workspace = true }
tokio-test = { workspace = true }
