[package]
name = "oprc-odgm"
version = "0.1.0"
edition = "2021"

[dependencies]
flare-dht = "0.1"
tokio={version = "1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = true
codegen-units = 1
