apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    platform: oaas
spec:
  replicas: 1
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 2
#      maxSurge: 3
  selector:
    matchLabels:
      app: gateway
      platform: oaas
  template:
    metadata:
      labels:
        app: gateway
        platform: oaas
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: gateway
                    platform: oaas
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: gateway
          image: ghcr.io/pawissanutt/oaas-rs/gateway
          env:
            - name: RUST_LOG
              value: INFO
            - name: HTTP_PORT
              value: "8080"
            - name: OPRC_MAX_POOL_SIZE
              value: "256"
            - name: OPRC_PM_URI
              value: http://package-manager
            
            
          ports:
            - containerPort: 8080
              name: http
          resources:
#            limits:
#              memory: 2G
#              cpu: '2'
            requests:
              cpu: '0.5'
              memory: 256M
          # imagePullPolicy: Always
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /q/health/live
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 30
          #   successThreshold: 1
          #   timeoutSeconds: 5
          # readinessProbe:
          #   failureThreshold: 100
          #   httpGet:
          #     path: /q/health/ready
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 3
          #   periodSeconds: 5
          #   successThreshold: 1
          #   timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    platform: oaas
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-np
  labels:
    app: gateway
    platform: oaas
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30222
      targetPort: 8080
