apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-runtime-manager
  labels:
    app: class-runtime-manager
    platform: oaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-runtime-manager
      platform: oaas
  template:
    metadata:
      labels:
        app: class-runtime-manager
        platform: oaas
    spec:
      automountServiceAccountToken: true
      serviceAccountName: class-runtime-manager-sa
      containers:
        - name: class-runtime-manager
          envFrom:
            - configMapRef:
                name: oaas-crm-config
            - configMapRef:
                name: oaas-cr-config
            - secretRef:
                name: oaas-crm-data
          image: ghcr.io/hpcclab/oaas/class-runtime-manager
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
              cpu: '1'
            requests:
              cpu: '0.25'
              memory: 256M
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: class-runtime-manager
spec:
  selector:
    app: class-runtime-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
