# Development values for CRM
replicaCount: 1

image:
  repository: ghcr.io/pawissanutt/oaas-rs/crm
  tag: "latest"
  pullPolicy: Always  # Always pull latest for dev

# No resource limits in dev for easier debugging
resources: {}

# Disable autoscaling in dev
autoscaling:
  enabled: false

config:
  profile: dev
  features:
    odgm: true
    knative: true  # Enable experimental features in dev
    prometheus: false  # Disable metrics in dev
    nfrEnforcement: false  # Disable enforcement in dev
    hpa: false
  enforcement:
    stabilitySeconds: 60   # Shorter stability window for dev
    cooldownSeconds: 120   # Shorter cooldown for dev
  analyzer:
    intervalSeconds: 120   # Less frequent analysis in dev

# Debug logging
logging:
  level: info,oprc_crm=debug
  format: plain

# Enable ingress for dev environment
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"  # Use HTTP for dev simplicity
  hosts:
    - host: crm-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []  # No TLS for dev environment

# Tolerations for dev nodes
tolerations:
  - key: "dev"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
