# Production values for CRM
replicaCount: 2

image:
  repository: ghcr.io/pawissanutt/oaas-rs/crm
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

config:
  profile: full
  features:
    odgm: true
    knative: false
    prometheus: true
    nfrEnforcement: true
    hpa: true
  enforcement:
    stabilitySeconds: 600  # 10 minutes
    cooldownSeconds: 900   # 15 minutes
  analyzer:
    intervalSeconds: 30    # More frequent analysis

# Production logging
logging:
  level: info
  format: json

# Enable ingress for external access
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: crm.oaas.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: crm-tls
      hosts:
        - crm.oaas.example.com

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Affinity for better distribution
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - oprc-crm
          topologyKey: kubernetes.io/hostname
