# CRM with Knative Operator for development
# This example shows minimal Knative Serving setup for local development
# Note: Knative Eventing has been removed as it's unnecessary for most use cases

replicaCount: 1

image:
  repository: ghcr.io/pawissanutt/oaas-rs/crm
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort
  port: 8088
  nodePort: 30088

config:
  profile: dev
  features:
    odgm: true
    knative: true  # Enable Knative template support in CRM
    prometheus: false
    nfrEnforcement: false
    hpa: false

# Enable only Knative Serving (no eventing needed)
knative:
  operator:
    enabled: true
    serving:
      enabled: true
      version: ""  # Latest version
      ingress:
        kourier:
          enabled: true
        istio:
          enabled: false
        contour:
          enabled: false
      dns:
        magic: true  # Use Magic DNS for development

# Minimal resources for development
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

# Disable features not needed for development
autoscaling:
  enabled: false

ingress:
  enabled: false

networkPolicy:
  enabled: false

prometheus:
  operator:
    enabled: false

env:
  RUST_LOG: "debug"
  OPRC_CRM_DEV_MODE: "true"
