# NodePort configuration for PM (Development/Testing)
replicaCount: 1

image:
  repository: ghcr.io/pawissanutt/oaas-rs/pm
  tag: "latest"
  pullPolicy: Always

# NodePort service for external access
service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080  # Access via http://<node-ip>:30080

config:
  storage:
    type: memory  # Use memory storage for simplicity
  
  crm:
    default:
      # Use NodePort URL for CRM if both are deployed with NodePort
      url: "http://localhost:30088"  # or use actual node IP
      timeout: 30
      retryAttempts: 2
  
  deployment:
    maxRetries: 1
    rollbackOnPartial: true
  
  package:
    deleteCascade: true

# Debug logging
logging:
  level: debug
  format: plain

# Disable ingress since we're using NodePort
ingress:
  enabled: false

# Resource limits for development
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
