# Production values for PM
replicaCount: 2

image:
  repository: ghcr.io/pawissanutt/oaas-rs/pm
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

config:
  server:
    host: "0.0.0.0"
    port: 8080
    workers: 4  # Explicit worker count for production
  
  storage:
    type: etcd
    etcd:
      endpoints: "etcd-cluster:2379,etcd-cluster-1:2379,etcd-cluster-2:2379"
      tls:
        insecure: false
        caCertPath: "/etc/ssl/etcd/ca.crt"
        clientCertPath: "/etc/ssl/etcd/client.crt"
        clientKeyPath: "/etc/ssl/etcd/client.key"
  
  crm:
    default:
      url: "https://crm.oaas.example.com:8088"
      timeout: 60  # Longer timeout for production
      retryAttempts: 5
    
    healthCheckInterval: 30  # More frequent health checks
    healthCacheTtl: 30
    
    circuitBreaker:
      failureThreshold: 3
      timeout: 120
  
  deployment:
    maxRetries: 3  # More retries in production
    rollbackOnPartial: false  # Keep partial successes
  
  package:
    deleteCascade: true  # Enable cascade delete in production

# Production logging
logging:
  level: info
  format: json

# Enable ingress for external access
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://oaas-ui.example.com"
  hosts:
    - host: pm.oaas.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pm-tls
      hosts:
        - pm.oaas.example.com

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Affinity for better distribution
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - oprc-pm
          topologyKey: kubernetes.io/hostname

# Node selector for dedicated nodes (optional)
# nodeSelector:
#   node-type: compute
