# PM with embedded etcd for development
replicaCount: 1

image:
  repository: ghcr.io/pawissanutt/oaas-rs/pm
  tag: "latest"
  pullPolicy: Always

config:
  storage:
    type: etcd
    etcd:
      useSubchart: true  # Use the embedded etcd
      tls:
        insecure: true
  
  crm:
    default:
      url: "http://oprc-crm:8088"
      timeout: 30
      retryAttempts: 2

# Enable embedded etcd for development
etcd:
  enabled: true
  replicaCount: 1  # Single node for dev
  
  # Disable auth for development
  auth:
    rbac:
      create: false
    token:
      enabled: false
  
  # Smaller resources for development
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  # Disable persistence for development (data will be lost on restart)
  persistence:
    enabled: false
  
  # Metrics disabled for dev
  metrics:
    enabled: false

# Debug logging
logging:
  level: debug
  format: plain
