apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

configMapGenerator:
  - name: oaas-crm-config
    behavior: merge
    options:
      disableNameSuffixHash: true
    literals:
      - OPRC_CRM_MONITORDISABLE="true"
      - OPRC_CRM_FEASIBLECHECKDISABLE="true"