[package]
name = "tools"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = {version = "0.1", features = ["sync"]}
oprc-pb ={ workspace=true }
tonic = "0.12"
tonic-reflection = { version = "0.12", features = ["server"] }
envconfig = "0.11.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dashmap = "6.1.0"

[[bin]]
name = "dev-echo-fn"

[[bin]]
name = "dev-pm"

[profile.release]
lto = true
codegen-units = 1
